title: Yong Yuan

name: YongYuan's homepage
description:  I am Yong Yuan. Willard is my English Name, which means great bravery. I completed my bachelor's degree in Faculty of Science at Xi'Dian University of science and technology of the electronics information on July 1, 2013.
url: http://yongyuan.name

# 自定义post url
permalink: /blog/:title.html
timezone: Asia/Chongqing

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    extensions:
    - autolink
    - footnotes
    - smart
hard_wrap: false
#  use_coderay: true
syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
gems:
  - jekyll-sitemap
